services:
  webserver:
    build: 
      context: ./compose/web
      dockerfile: webserver.Containerfile
    # image: bitnami/laravel:11-debian-12
    tty: true
    ports:
      - "8000:8000"
    volumes:
      - ./laravelProject:/app
    environment:
      APP_NAME: Laravel
      DB_CONNECTION: pgsql
      DB_HOST: backend-postgresql
      DB_PORT: 5432 
      DB_USERNAME: laravel
      DB_PASSWORD: password
      DB_DATABASE: laravel
      REDIS_HOST: cache
      REDIS_CLIENT: predis
      REDIS_PORT: 6379
  
    networks:
      - caching
      - dataplane
  cache:
    image: redis:bookworm
    tty: true
    networks:
      - caching

  backend-postgresql:
    image: postgres:17
    # Use postgres/example user/password credential
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - databasedata:/var/lib/postgresql/data/pgdata
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: laravel
      POSTGRES_DB: laravel
      POSTGRES_INITDB_ARGS:  "--auth-host=scram-sha-256"
      POSTGRES_HOST_AUTH_METHOD: scram-sha-256
      PGDATA: /var/lib/postgresql/data/pgdata
    networks:
      - dataplane

volumes:
  webservice:
  databasedata:

networks:
  dataplane:
    driver: bridge
  caching:
    driver: bridge