# WEBSERVER PROVISIONING
FROM debian:12

ENV POSTGRES_PORT 5432
ENV POSTGRES_LISTEN_IP 0.0.0.0
ENV POSTGRES_VOLUME /var/databasedata

VOLUME ["/var/databasedata"]
EXPOSE 5432


RUN apt update
RUN apt-get install -y curl ca-certificates lsb-release gettext
RUN install -d /usr/share/postgresql-common/pgdg

## INSTALLING THE REPO ORIGIN
RUN curl -o /usr/share/postgresql-common/pgdg/apt.postgresql.org.asc --fail https://www.postgresql.org/media/keys/ACCC4CF8.asc
RUN sh -c 'echo "deb [signed-by=/usr/share/postgresql-common/pgdg/apt.postgresql.org.asc] https://apt.postgresql.org/pub/repos/apt $(lsb_release -cs)-pgdg main" > /etc/apt/sources.list.d/pgdg.list'

## INSTALLING POSTGRESQL
RUN apt update
RUN apt install postgresql-17 postgresql-client-17 locales-all -y

### PREPARING CLUSTERS
COPY pg_hba.conf /etc/postgresql/17/main/pg_hba.conf
COPY postgresql.conf /etc/postgresql/17/main/postgresql.conf.tmp

RUN envsubst < /etc/postgresql/17/main/postgresql.conf.tmp > /etc/postgresql/17/main/postgresql.conf

RUN chown -R postgres:postgres /var/databasedata
RUN pg_createcluster 17 -d /var/databasedata/ -l /var/log/postgresql/postgresql-16-main.log initdb
